services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8872:80
    depends_on:
      - app
    container_name: project_forum_nginx

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    container_name: project_forum_app

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 8072:3306
    environment:
      MYSQL_DATABASE: laravel_forum_db
      MYSQL_ROOT_PASSWORD: root
    container_name: project_forum_db
